### ISSUE TITLE
create service registry fails "panic: message "service.info.termsCheck" not found in language "en""

### ISSUE THREAD

**Issue by famartinrh** [redhat-developer/app-services-cli#807]
Create service registry is failing in the last version
```
$ rhoas service-registry create famartin-test-1
panic: message "service.info.termsCheck" not found in language "en"

goroutine 1 [running]:
github.com/nicksnyder/go-i18n/v2/i18n.(*Localizer).MustLocalize(0xc000451600, 0xc0001af7d0, 0x1c61c93, 0x8)
	/home/runner/go/pkg/mod/github.com/nicksnyder/go-i18n/v2@v2.1.2/i18n/localizer.go:211 +0x7c
github.com/redhat-developer/app-services-cli/pkg/localize/goi18n.(*Goi18n).MustLocalize(0xc000405950, 0x1c7595c, 0x17, 0xc000632060, 0x1, 0x1, 0x0, 0x2af7f68)
	/home/runner/work/app-services-cli/app-services-cli/pkg/localize/goi18n/go_i18n.go:84 +0x165
github.com/redhat-developer/app-services-cli/pkg/cmd/registry/create.runCreate(0xc000594b40, 0x4, 0x2aa52e0)
	/home/runner/work/app-services-cli/app-services-cli/pkg/cmd/registry/create/create.go:134 +0xd8a
github.com/redhat-developer/app-services-cli/pkg/cmd/registry/create.NewCreateCommand.func1(0xc0001bca00, 0xc000598700, 0x1, 0x1, 0x0, 0x0)
	/home/runner/work/app-services-cli/app-services-cli/pkg/cmd/registry/create/create.go:84 +0xf3
github.com/spf13/cobra.(*Command).execute(0xc0001bca00, 0xc0005986e0, 0x1, 0x1, 0xc0001bca00, 0xc0005986e0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc00025cf00, 0x1e84600, 0xd, 0xc00025cf00)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
	/home/runner/work/app-services-cli/app-services-cli/cmd/rhoas/main.go:59 +0x3c5
$ rhoas version
rhoas version 0.26.0-alpha3
```

**Comment by wtrocki** [comment]
Amazing! We haven't seen this because all of us accepted terms and conditions. 
To accept it you need to use UI :)

**Comment by wtrocki** [comment]
See #808

**Comment by wtrocki** [comment]
Released alpha
